<a href="https://colab.research.google.com/github/marekhennig/175IC-machine-learning/blob/main/Zad_Wyklad_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import numpy as np

tabZer = [0,0,0,0,0,0,0,0,0,0]
tabPiatek = [5,5,5,5,5,5,5,5,5,5]
tabPrzedzial = []
for n in range(10,50,1):
    tabPrzedzial.append(n)

macierz = [[0 for col in range(3)] for row in range(3)]
z=0
for m in range(3):
  for n in range(3):
      macierz[m][n] = z
      z=z+1

macierzJednostkowa = [[0 for col in range(3)] for row in range(3)]
for m in range(3):
  macierzJednostkowa[m][m] = 1

macierzGaussa = np.random.normal(3, 2.5 , size=(5,5))
macierzFloat = np.arange(0.01,1.01,0.01).reshape((10,10))
tabOneToZero = np.linspace(0,1,20)

tabRandom = np.random.randint(1,25,25)
tabRandom = tabRandom.reshape((5,5))
print("Randomowa macierz: " )
print(tabRandom)
print("Suma Randomowej macierzy: ",tabRandom.sum())
print("Średnia Randomowej macierzy: ", tabRandom.mean())
print("Std(standardowa dewiacja) Randomowej macierzy: ", tabRandom.std())

tabRandomSum = tabRandom.sum(axis=0)

print("Suma każdej kolumny")
print(tabRandomSum)
tabRandWithSum = np.append(tabRandom, tabRandomSum)
tabRandWithSum = tabRandWithSum.reshape(6,5)
print("Randomowa macierz z sumą każdej kolumny")
print(tabRandWithSum)

tabRandBig = np.random.randint(0, 100, 25)
tabRandBig = tabRandBig.reshape((5,5))
print("Macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100): ")
print(tabRandBig)
print("Mediana: ", np.median(tabRandBig))
print("Najmniejsza liczba: ", tabRandBig.min())
print("Największa liczba: ", tabRandBig.max())
tabRandRectang = np.random.randint(0, 100, 6)
tabRandRectang = tabRandRectang.reshape((2,3))
print("Macierz prostokątna: ")
print(tabRandRectang)
print("Macierz prostokątna transponowana: ")
print(tabRandRectang.transpose())
macierzPreLastOne = np.random.randint(100, size=(3,3))
macierzPreLastestOne = np.random.randint(100, size=(3,3))
print("Macierz 1: ")
print(macierzPreLastOne)
print("Macierz 2: ")
print(macierzPreLastestOne)
print("Macierz wynikowa dodawania 1 i 2: " )
print(np.add(macierzPreLastOne, macierzPreLastestOne))

macierzLastOne = np.random.randint(100, size=(6,3))
macierzLastestOne = np.random.randint(100, size=(3,6))
print("Macierz 1: ")
print(macierzLastOne)
print("Macierz 2: ")
print(macierzLastestOne)
print("Macierz wynikowa mnożenia za pomocą multiply: " )
print(np.dot(macierzLastOne, macierzLastestOne))
print("Macierz wynikowa mnożenia za pomocą matmul: " )
print(np.matmul(macierzLastOne, macierzLastestOne))



Randomowa macierz: 
[[10 24  5 21 23]
 [19 14 20 11 16]
 [21 23 20  8  1]
 [16 24  7 18 20]
 [22 12 23 22  7]]
Suma Randomowej macierzy:  407
Średnia Randomowej macierzy:  16.28
Std(standardowa dewiacja) Randomowej macierzy:  6.660450435218326
Suma każdej kolumny
[88 97 75 80 67]
Randomowa macierz z sumą każdej kolumny
[[10 24  5 21 23]
 [19 14 20 11 16]
 [21 23 20  8  1]
 [16 24  7 18 20]
 [22 12 23 22  7]
 [88 97 75 80 67]]
Macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100): 
[[20 85 96  8 99]
 [59 28 35 22  2]
 [63 17 90 18 35]
 [98 54 36 64 29]
 [ 0 91 99  6 30]]
Mediana:  35.0
Najmniejsza liczba:  0
Największa liczba:  99
Macierz prostokątna: 
[[ 0 41 73]
 [66  6 80]]
Macierz prostokątna transponowana: 
[[ 0 66]
 [41  6]
 [73 80]]
Macierz 1: 
[[94 29 37]
 [15 18 78]
 [69 58 76]]
Macierz 2: 
[[ 9  7 43]
 [ 7 93 83]
 [39 58 42]]
Macierz wynikowa dodawania 1 i 2: 
[[103  36  80]
 [ 22 111 161]
 [108 116 118]]
Macierz 1: 
[[89 58 94]
 [94 47 32]
 [74 96 20]
 [51 2